
-- INSERTS FOR TESTING CLIENT SIDE
delete from OrderItem where 1=1;

delete from [Order] where 1=1;
DBCC CHECKIDENT([Order], RESEED, 0);
delete from [Order] where 1=1;

delete from [Address] where 1=1;
DBCC CHECKIDENT([Address], RESEED, 0);
delete from [Address] where 1=1;

DBCC CHECKIDENT (Item, RESEED, 0);
delete from Item where 1=1;
DBCC CHECKIDENT (Item, RESEED, 0);
delete from Permissions where 1=1;
DBCC CHECKIDENT (Permissions, RESEED, 0);

delete from Category where 1=1;
DBCC CHECKIDENT(Category, RESEED, 0);
delete from Category where 1=1;

delete from [User] where 1=1;
DBCC CHECKIDENT ([User], RESEED, 0);
delete from [User] where 1=1;

insert into Category ( [Name]) values ( 'Beverages');
insert into Category ( [Name]) values ( 'Bakery');
insert into Category ( [Name]) values ( 'Canned/Jarred Goods');
insert into Category ( [Name]) values ( 'Dairy');
insert into Category ( [Name]) values ( 'Dry/Baking Goods');
insert into Category ( [Name]) values ( 'Frozen Foods');
insert into Category ( [Name]) values ( 'Meat');
insert into Category ( [Name]) values ( 'Produce');
insert into Category ( [Name]) values ( 'Cleaners');
insert into Category ( [Name]) values ( 'Paper Goods');
insert into Category ( [Name]) values ( 'Personal Care');
insert into Category ( [Name]) values ( 'Other');
go
insert into Permissions (PermissionName)
values ('Customer'), ('Admin');
go
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Gus', 'Jost', 'gjost0@trellian.com', 'hFMNCbBPRMzm', '332-411-2147',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Trude', 'Bes', 'tbes1@sogou.com', 'okz1XfRsv3', '815-234-2158',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Lew', 'Dedmam', 'ldedmam2@yale.edu', 'JdO5Vu4e', '286-724-9302',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Fawne', 'MacGinney', 'fmacginney3@ox.ac.uk', 'kUkvzLfV', '547-731-6904',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Benito', 'Cavan', 'bcavan4@bizjournals.com', 'DRXO5Pf', '295-277-3367',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Shepperd', 'Font', 'sfont5@state.gov', 'jJcb14FzD7M', '278-950-5474',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Garrot', 'Dumigan', 'gdumigan6@redcross.org', '1gzgAxbM8Woa', '342-855-3265',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Auria', 'Hogbourne', 'ahogbourne7@sitemeter.com', '0kxpjx04Chxv', '858-276-4006',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Shandee', 'McQuillen', 'smcquillen8@scientificamerican.com', 'svED2o3ujNUr', '459-863-0224',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Enid', 'Caisley', 'ecaisley9@engadget.com', 'tEmR3Do2j', '302-808-2509',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Rodina', 'Ivery', 'riverya@bing.com', 'lJ2ITaB75IU', '300-475-8336',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Gloriane', 'Fetters', 'gfettersb@marketwatch.com', 's1OTmegL', '208-807-7087',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Gloriana', 'Nowakowska', 'gnowakowskac@acquirethisname.com', 'rIr474X', '211-450-5946',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Ari', 'Vawton', 'avawtond@ted.com', 'siUFdNoGzo', '997-861-0986',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Katerine', 'Baitson', 'kbaitsone@ftc.gov', 'ooSucRSjIj6', '292-228-2748',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Brandice', 'Espinosa', 'bespinosaf@usda.gov', '72o3ou', '451-254-2350',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Rebbecca', 'Gives', 'rgivesg@themeforest.net', 'jTerUEkK', '813-503-3034',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Shurlock', 'Hame', 'shameh@princeton.edu', 'tkvAujjV', '841-933-0454',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Jeth', 'Nutbeem', 'jnutbeemi@jigsy.com', 'FSDd5RM83SdY', '268-312-1218',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Rozamond', 'Canada', 'rcanadaj@macromedia.com', '6u3gmH1gO', '167-934-6702',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Bertram', 'Slamaker', 'bslamakerk@etsy.com', 'S8R6F2x', '132-456-3145',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Cesar', 'Haycroft', 'chaycroftl@blinklist.com', '3Pkqn23z8r', '788-945-7628',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Muffin', 'Starbuck', 'mstarbuckm@163.com', 'Mgi4gvx', '831-404-4955',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Tara', 'Egginson', 'tegginsonn@macromedia.com', 'h7SctcXi', '962-408-6748',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Brett', 'Giovanazzi', 'bgiovanazzio@forbes.com', 'gVjDpdi8NswH', '794-593-4275',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Gusty', 'Goldfinch', 'ggoldfinchp@flickr.com', 'eGbFQ7rw2', '647-954-3973',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Mario', 'Timbridge', 'mtimbridgeq@oracle.com', 'iC4OgnD4O', '619-633-5692',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Leupold', 'Cawthra', 'lcawthrar@weather.com', 'RNGr763g6F7M', '997-876-4161',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Grazia', 'Duffy', 'gduffys@wufoo.com', 'C8Tt7ijh5um', '515-376-3823',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Maia', 'Waterstone', 'mwaterstonet@so-net.ne.jp', '3cAJy2kvpnzW', '918-873-9733',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Catharina', 'MacFadzan', 'cmacfadzanu@1und1.de', 'jEwQDk', '182-432-7094',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Salvador', 'Blumire', 'sblumirev@pen.io', 'hNi5ONXwcj', '230-174-3231',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Hermina', 'Windrus', 'hwindrusw@webeden.co.uk', 'QNzYoD', '709-192-1811',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Francesco', 'Wheldon', 'fwheldonx@icq.com', 'te5w7v', '893-413-3020',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Josie', 'Ethridge', 'jethridgey@photobucket.com', 'LlvdOiZf', '250-591-5214',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Leopold', 'Mavin', 'lmavinz@hp.com', 'zmTlQmzuG', '972-820-6018',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Francisca', 'Garnsey', 'fgarnsey10@ycombinator.com', 'wLwlgn', '192-335-4457',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Cate', 'Enrico', 'cenrico11@blog.com', 'yx6qjYglN', '157-792-0369',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Filbert', 'Woolfenden', 'fwoolfenden12@uiuc.edu', 'wtvKRFUcZ', '298-187-1961',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Shanta', 'Craddock', 'scraddock13@1688.com', '7AiyycQZ', '407-948-0327',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Dianemarie', 'Steels', 'dsteels14@themeforest.net', 'i7SFH8q8fc', '776-227-1015',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Libbie', 'Bielfeldt', 'lbielfeldt15@nhs.uk', '19lJljSzqs4', '155-759-1883',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Adan', 'Murtimer', 'amurtimer16@msn.com', 'suFPhrs3a1wT', '566-377-9270',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Casey', 'Garret', 'cgarret17@bloglovin.com', 'GN3JZH', '410-404-7650',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Harbert', 'Dacke', 'hdacke18@cam.ac.uk', 'qWLftwCSeaqs', '132-824-6613',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Billie', 'Kennham', 'bkennham19@mit.edu', 'G1JF7746FvHs', '411-994-7592',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Cordy', 'Toynbee', 'ctoynbee1a@ft.com', 'bIhTLHF5VaU', '462-945-2108',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Peggy', 'Goddman', 'pgoddman1b@cam.ac.uk', 'bP0teaGAbiV', '768-985-1768',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Faun', 'Peery', 'fpeery1c@youtube.com', 'ZIAqtq', '269-742-1847',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Steffen', 'Yezafovich', 'syezafovich1d@youku.com', 'EX9KfAZCiv2', '506-202-7256',2);
go

-- INSERTS FOR TESTING CLIENT SIDE
set IDENTITY_INSERT [Address] on;
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (1, 1, '448 Sloan Circle', 'Minneapolis', 'MN', 55102, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (2, 2, '747 Vermont Point', 'Minneapolis', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (3, 3, '9 Vernon Park', 'St. Paul', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (4, 4, '4557 Karstens Park', 'St. Paul', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (5, 5, '3 Washington Place', 'Minneapolis', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (6, 6, '75428 Del Mar Crossing', 'Minneapolis', 'MN', 55408, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (7, 7, '6634 Center Hill', 'Minneapolis', 'MN', 55101, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (8, 8, '233 Shoshone Road', 'Minneapolis', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (9, 9, '61659 Algoma Lane', 'St. Paul', 'MN', 55101, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (10, 10, '74514 Anhalt Pass', 'St. Paul', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (11, 11, '5293 Claremont Court', 'Minneapolis', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (12, 12, '9162 Duke Way', 'Minneapolis', 'MN', 55102, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (13, 13, '51925 Elgar Terrace', 'Minneapolis', 'MN', 55408, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (14, 14, '021 Jenna Point', 'Minneapolis', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (15, 15, '79034 Village Green Court', 'Minneapolis', 'MN', 55104, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (16, 16, '40 Colorado Way', 'Minneapolis', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (17, 17, '43 Barby Junction', 'St. Paul', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (18, 18, '2795 Fuller Way', 'St. Paul', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (19, 19, '5059 Debra Plaza', 'St. Paul', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (20, 20, '2468 Bunting Hill', 'Minneapolis', 'MN', 55408, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (21, 21, '9967 Cardinal Pass', 'Minneapolis', 'MN', 55408, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (22, 22, '8462 Thierer Center', 'St. Paul', 'MN', 55102, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (23, 23, '84 Basil Avenue', 'Minneapolis', 'MN', 55104, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (24, 24, '3 Sycamore Circle', 'St. Paul', 'MN', 55103, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (25, 25, '3 Autumn Leaf Hill', 'St. Paul', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (26, 26, '5 Forest Run Court', 'Minneapolis', 'MN', 55102, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (27, 27, '2835 Lakewood Junction', 'St. Paul', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (28, 28, '80 Summit Circle', 'St. Paul', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (29, 29, '4 Ronald Regan Avenue', 'Minneapolis', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (30, 30, '0 Golden Leaf Lane', 'St. Paul', 'MN', 55104, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (31, 31, '62762 Summerview Junction', 'St. Paul', 'MN', 55104, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (32, 32, '3 Erie Point', 'Minneapolis', 'MN', 55102, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (33, 33, '733 Reinke Trail', 'Minneapolis', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (34, 34, '56467 Melvin Place', 'Minneapolis', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (35, 35, '8387 Northwestern Hill', 'St. Paul', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (36, 36, '2162 Truax Circle', 'St. Paul', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (37, 37, '00 Sheridan Point', 'St. Paul', 'MN', 55408, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (38, 38, '6025 Nelson Park', 'St. Paul', 'MN', 55104, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (39, 39, '64 Kenwood Pass', 'Minneapolis', 'MN', 55102, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (40, 40, '77 Hauk Road', 'Minneapolis', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (41, 41, '44928 Thackeray Parkway', 'Minneapolis', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (42, 42, '9 Buhler Park', 'Minneapolis', 'MN', 55408, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (43, 43, '71 Muir Terrace', 'St. Paul', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (44, 44, '4 Division Court', 'Minneapolis', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (45, 45, '7 Summit Circle', 'St. Paul', 'MN', 55103, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (46, 46, '62 Moland Park', 'St. Paul', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (47, 47, '6 Birchwood Plaza', 'St. Paul', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (48, 48, '8 Darwin Point', 'Minneapolis', 'MN', 55104, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (49, 49, '6 Division Avenue', 'Minneapolis', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (50, 50, '115 Merry Terrace', 'St. Paul', 'MN', 55404, 'US');
set IDENTITY_INSERT [Address] off;

go
insert into [Order] (UserId, TotalCost, DateCreated) values (1, 10, '3/8/2022');
insert into [Order] (UserId, TotalCost, DateCreated) values (2, 92, '3/11/2022');
insert into [Order] (UserId, TotalCost, DateCreated) values (3, 68, '9/19/2021');

go

insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Yogurt - Plain', 'felis sed lacus morbi', 83.27, 84);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Beef - Rib Eye Aaa', 'nunc donec', 51.34, 66);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Wine - Alsace Gewurztraminer', 'et eros vestibulum ac', 31.79, 7);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Cake - Night And Day Choclate', 'nam congue', 96.42, 49);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Lettuce - Boston Bib', 'libero non mattis pulvinar nulla', 19.88, 52);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Eggplant - Regular', 'volutpat', 77.61, 24);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Oil - Grapeseed Oil', 'ut nunc vestibulum', 20.02, 54);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Cheese - Woolwich Goat, Log', 'massa quis augue luctus tincidunt', 13.75, 72);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Cod - Black Whole Fillet', 'nullam sit amet', 74.84, 98);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Lid Coffeecup 12oz D9542b', 'vivamus', 13.57, 4);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Numi - Assorted Teas', 'gravida sem praesent id', 43.58, 26);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Raspberries - Frozen', 'malesuada in imperdiet et commodo', 94.28, 12);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Carbonated Water - Blackberry', 'ac tellus semper', 90.42, 32);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Canada Dry', 'nec sem duis aliquam', 2.28, 94);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Flour - Fast / Rapid', 'libero quis orci nullam molestie', 97.12, 34);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Cheese - Fontina', 'diam cras', 3.84, 9);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Sproutsmustard Cress', 'sit', 52.93, 70);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Pie Box - Cello Window 2.5', 'faucibus cursus', 16.82, 10);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Juice - Propel Sport', 'dapibus dolor', 50.7, 33);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Cheese - Goat', 'sollicitudin', 95.94, 15);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Coconut - Creamed, Pure', 'at', 91.86, 1);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Broom - Push', 'eget elit sodales scelerisque', 97.75, 27);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Macaroons - Two Bite Choc', 'praesent lectus', 67.05, 75);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Cheese - Brie,danish', 'integer aliquet massa id', 96.37, 54);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Tortillas - Flour, 12', 'dignissim vestibulum vestibulum', 38.31, 73);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Lamb - Loin Chops', 'metus sapien ut nunc vestibulum', 28.28, 91);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Pastry - Banana Tea Loaf', 'mauris viverra diam vitae', 47.82, 72);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Beer - Corona', 'magna vestibulum', 52.42, 2);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Juice - Orange, Concentrate', 'ultrices enim lorem ipsum dolor', 48.41, 56);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Pork - Sausage, Medium', 'etiam pretium iaculis justo', 80.93, 25);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Cumin - Ground', 'mattis odio donec', 21.66, 40);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Pepper - Sorrano', 'felis ut at dolor', 63.42, 50);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Nut - Almond, Blanched, Sliced', 'eu mi nulla', 10.77, 59);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Juice - Apple, 1.36l', 'ultrices', 30.43, 30);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Carbonated Water - Orange', 'eget elit sodales', 14.66, 100);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Sauce - Black Current, Dry Mix', 'cum sociis natoque penatibus', 40.39, 69);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Cheese - Bocconcini', 'vestibulum ante', 69.33, 94);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Prunes - Pitted', 'ultrices mattis odio donec vitae', 46.86, 27);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Versatainer Nc - 9388', 'rutrum', 58.88, 24);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Tart Shells - Sweet, 3', 'non mattis pulvinar', 59.21, 18);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Food Colouring - Orange', 'egestas metus aenean fermentum', 72.55, 74);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Nescafe - Frothy French Vanilla', 'sem', 41.16, 82);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Barramundi', 'at', 73.95, 26);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'White Fish - Filets', 'elementum', 48.71, 21);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Bread - Bistro White', 'blandit', 97.25, 22);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Chips Potato Salt Vinegar 43g', 'nulla nisl nunc nisl', 16.8, 42);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Duck - Breast', 'posuere cubilia', 45.73, 66);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Cheese - La Sauvagine', 'tempus sit', 65.57, 82);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Wine - Red, Gallo, Merlot', 'neque sapien placerat ante', 5.47, 12);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Wine - Sherry Dry Sack, William', 'luctus cum sociis', 21.42, 67);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Beans - Long, Chinese', 'condimentum curabitur in libero', 65.16, 6);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Tomatoes', 'dolor sit amet consectetuer', 12.64, 41);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Bread - White Epi Baguette', 'quis libero', 41.55, 70);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Lamb - Leg, Bone In', 'congue', 33.52, 86);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Sesame Seed', 'augue vel accumsan tellus', 21.43, 2);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Veal Inside - Provimi', 'ut erat id mauris vulputate', 21.67, 16);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Cake - Mini Cheesecake', 'cursus urna ut', 76.77, 44);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Oil - Cooking Spray', 'nulla integer pede', 26.45, 43);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Chocolate - Milk, Callets', 'nisl nunc nisl duis bibendum', 53.83, 60);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Hold Up Tool Storage Rack', 'tincidunt nulla mollis molestie lorem', 86.05, 65);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Bread - Granary Small Pull', 'proin eu mi nulla ac', 59.88, 15);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Coffee - Cafe Moreno', 'elementum', 51.83, 15);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Icecream - Dstk Super Cone', 'donec pharetra', 33.23, 66);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Lentils - Red, Dry', 'imperdiet et commodo vulputate', 60.06, 46);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Tahini Paste', 'tortor duis mattis egestas', 83.45, 3);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Bread - French Baquette', 'nisl', 90.67, 73);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Cherries - Bing, Canned', 'vulputate ut ultrices vel augue', 15.25, 16);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Pepper - Julienne, Frozen', 'elit sodales scelerisque', 66.88, 12);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Cake Slab', 'orci', 12.47, 50);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Beef - Tenderloin - Aa', 'sit amet eros', 92.25, 8);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Tart Shells - Barquettes, Savory', 'massa id nisl', 99.34, 43);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Venison - Liver', 'posuere cubilia curae donec', 49.21, 35);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Wine - Champagne Brut Veuve', 'vel nulla eget', 14.79, 54);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Beef - Top Butt Aaa', 'praesent lectus', 3.07, 54);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Devonshire Cream', 'bibendum morbi non', 95.43, 59);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Bacardi Mojito', 'hac', 20.36, 62);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Pepper - Scotch Bonnet', 'nulla ac enim in tempor', 88.03, 44);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Soup - Campbells Mac N Cheese', 'nunc purus phasellus in', 33.51, 99);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Noodles - Steamed Chow Mein', 'dolor morbi', 74.64, 31);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Banana - Green', 'lacus morbi', 47.37, 97);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Apples - Spartan', 'ultrices erat tortor sollicitudin', 2.96, 17);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Muffin Batt - Ban Dream Zero', 'ultrices mattis odio', 21.11, 28);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Venison - Ground', 'sapien urna', 20.37, 35);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Wine - White, Mosel Gold', 'rutrum ac lobortis vel', 69.84, 91);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Oil - Olive, Extra Virgin', 'sagittis sapien cum sociis natoque', 40.83, 45);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Pasta - Gnocchi, Potato', 'cursus urna ut', 2.85, 71);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Fond - Chocolate', 'quis augue', 45.83, 25);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Pie Pecan', 'in', 94.48, 95);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Octopus', 'augue', 63.33, 13);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'The Pop Shoppe - Grape', 'mauris', 63.05, 48);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Pepper - Cubanelle', 'duis ac nibh fusce lacus', 45.42, 32);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Five Alive Citrus', 'a ipsum integer a nibh', 50.83, 79);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Honey - Comb', 'posuere cubilia curae mauris viverra', 21.66, 83);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Cheese - Mascarpone', 'eget elit sodales scelerisque mauris', 51.56, 59);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Tuna - Canned, Flaked, Light', 'faucibus orci luctus', 65.86, 4);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Wine - White, French Cross', 'hendrerit at vulputate vitae', 75.68, 30);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'General Purpose Trigger', 'a nibh in quis justo', 85.23, 18);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Cookie Double Choco', 'integer aliquet massa id lobortis', 93.29, 94);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Marjoram - Fresh', 'enim sit amet nunc', 57.71, 82);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Assorted Desserts', 'augue quam sollicitudin', 15.94, 32);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Cheese - Sheep Milk', 'lacus at turpis donec posuere', 62.34, 19);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Onions - Cippolini', 'erat', 38.66, 13);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Sugar - Brown, Individual', 'dui vel nisl duis', 38.86, 6);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Yogurt - Banana, 175 Gr', 'nulla elit ac', 4.67, 79);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Flower - Daisies', 'porttitor lacus at turpis', 9.63, 15);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Wine - Red, Cabernet Sauvignon', 'tincidunt nulla', 3.89, 97);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Plate Foam Laminated 9in Blk', 'in libero ut', 85.62, 100);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Sauce - Sesame Thai Dressing', 'ullamcorper purus', 48.52, 74);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Ham - Cooked Bayonne Tinned', 'tellus nulla', 29.64, 59);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Fennel - Seeds', 'ipsum primis', 95.22, 30);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Horseradish Root', 'aenean fermentum', 25.86, 15);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Dry Ice', 'nulla integer', 77.16, 71);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Pastry - Carrot Muffin - Mini', 'purus phasellus', 90.22, 49);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Buffalo - Tenderloin', 'odio in hac', 95.09, 87);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Wine - Barolo Fontanafredda', 'tristique fusce congue diam', 34.53, 73);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Beer - Steamwhistle', 'sapien', 98.19, 45);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Kellogs Cereal In A Cup', 'id nisl venenatis lacinia', 96.78, 71);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Lamb - Sausage Casings', 'suscipit ligula', 57.06, 22);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Beans - Butter Lrg Lima', 'lacinia aenean sit amet justo', 4.21, 57);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Nantucket - Pomegranate Pear', 'venenatis tristique', 21.9, 73);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Tofu - Firm', 'turpis eget elit sodales scelerisque', 15.5, 24);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Napkin Colour', 'lacus curabitur at ipsum ac', 81.13, 8);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Mustard Prepared', 'lectus in', 9.81, 88);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Tomatoes - Heirloom', 'velit donec diam neque vestibulum', 41.33, 83);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Turnip - Mini', 'vulputate luctus', 86.84, 7);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Muffin Mix - Lemon Cranberry', 'quisque', 89.69, 52);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Apple - Royal Gala', 'in tempor', 86.81, 12);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Soup - Knorr, Country Bean', 'orci eget orci vehicula condimentum', 20.02, 19);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Cakes Assorted', 'phasellus sit amet', 22.62, 74);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Neckerchief Blck', 'ut at', 23.85, 91);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Cake Sheet Combo Party Pack', 'quam nec dui luctus rutrum', 86.11, 18);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Cleaner - Bleach', 'vivamus vel nulla eget', 81.82, 2);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'V8 Pet', 'congue elementum in', 13.53, 53);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Fireball Whisky', 'curae mauris', 6.71, 71);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Brandy - Orange, Mc Guiness', 'in', 84.63, 6);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Wine - Red, Colio Cabernet', 'cursus urna', 21.72, 38);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Mushroom - Chantrelle, Fresh', 'nam congue risus', 31.21, 92);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Cut Wakame - Hanawakaba', 'vestibulum vestibulum ante ipsum', 59.01, 63);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Nori Sea Weed', 'augue vel accumsan', 48.6, 85);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Bread - Sour Sticks With Onion', 'sit amet nunc', 84.32, 81);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Duck - Breast', 'sapien urna pretium nisl', 41.89, 39);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Gherkin', 'tincidunt eget tempus vel pede', 4.01, 83);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Sage - Rubbed', 'integer', 2.86, 53);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Cup - Paper 10oz 92959', 'cras non', 76.43, 16);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Gatorade - Cool Blue Raspberry', 'neque duis bibendum morbi', 67.12, 35);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Loquat', 'nisi volutpat eleifend', 18.06, 75);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Tuna - Loin', 'eleifend donec ut dolor', 59.31, 77);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Syrup - Monin - Passion Fruit', 'sollicitudin mi sit amet lobortis', 86.3, 77);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Wine - Saint - Bris 2002, Sauv', 'tincidunt', 55.4, 34);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Fruit Salad Deluxe', 'ligula sit amet eleifend pede', 75.89, 31);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Cabbage - Green', 'luctus', 30.85, 26);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Pomegranates', 'amet sem fusce consequat nulla', 76.92, 62);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Longos - Chicken Caeser Salad', 'quam sapien varius ut', 37.25, 98);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Cheese - Fontina', 'nulla nunc purus phasellus', 47.04, 4);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Duck - Whole', 'fusce posuere felis', 97.41, 10);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Beer - Labatt Blue', 'vulputate', 66.87, 27);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Sprouts - Brussel', 'sapien', 91.55, 48);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Onion Powder', 'ultrices posuere cubilia', 22.59, 77);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Onions - Red Pearl', 'leo', 88.14, 39);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Pastry - Butterscotch Baked', 'neque libero convallis', 71.12, 27);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Cheese - St. Paulin', 'ipsum', 63.35, 72);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Cheese - Brie Roitelet', 'sapien', 20.5, 36);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Edible Flower - Mixed', 'quis justo', 92.62, 89);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Soupcontfoam16oz 116con', 'morbi', 28.0, 48);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Soup Campbells Beef With Veg', 'est', 44.3, 52);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Rosemary - Primerba, Paste', 'in faucibus orci', 25.02, 88);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Smoked Paprika', 'sit amet', 65.13, 79);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Silicone Parch. 16.3x24.3', 'tempus', 6.63, 49);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Pork - Caul Fat', 'velit vivamus vel nulla eget', 71.39, 47);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Sea Urchin', 'interdum eu tincidunt in', 8.65, 93);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Coffee Decaf Colombian', 'sit amet justo morbi', 44.62, 86);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Lettuce - Iceberg', 'lorem', 53.74, 56);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Nut - Almond, Blanched, Whole', 'nam nulla integer pede justo', 17.63, 64);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Creme De Cacao White', 'massa tempor convallis', 50.85, 18);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Otomegusa Dashi Konbu', 'neque aenean auctor', 13.78, 28);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Pastry - Choclate Baked', 'et', 15.63, 48);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Liqueur Banana, Ramazzotti', 'nam', 42.79, 27);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Taro Leaves', 'faucibus cursus', 62.01, 94);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Bread - French Stick', 'habitasse platea dictumst morbi', 76.47, 34);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Sprite, Diet - 355ml', 'suscipit ligula in', 27.48, 51);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Beef Ground Medium', 'ut volutpat sapien', 78.73, 2);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Bread - Dark Rye', 'orci', 5.46, 87);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Halibut - Steaks', 'vitae nisi', 57.14, 53);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Neckerchief Blck', 'eros', 76.03, 35);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Beef - Inside Round', 'nibh in lectus pellentesque at', 40.23, 93);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Cake Sheet Combo Party Pack', 'sed lacus', 6.3, 92);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Praline Paste', 'ligula', 23.25, 66);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Juice - Mango', 'at nibh in hac', 62.18, 9);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Lettuce - Radicchio', 'euismod scelerisque quam turpis adipiscing', 74.29, 46);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Mushroom - Chantrelle, Fresh', 'consequat', 2.62, 76);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Basil - Pesto Sauce', 'id sapien in sapien', 51.22, 86);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Sherry - Dry', 'erat', 57.15, 24);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Oven Mitts 17 Inch', 'eget orci', 69.91, 63);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Pasta - Penne, Rigate, Dry', 'at nibh in hac habitasse', 35.58, 30);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Appetizer - Cheese Bites', 'volutpat in congue etiam justo', 92.08, 95);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Sobe - Tropical Energy', 'odio', 93.38, 82);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Wine - Baron De Rothschild', 'metus sapien ut nunc', 14.37, 38);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Muffins - Assorted', 'diam erat fermentum', 41.69, 89);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Sole - Fillet', 'lorem', 11.93, 85);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Sauce - Hp', 'consectetuer adipiscing elit proin interdum', 42.57, 41);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Soup - Campbells - Tomato', 'venenatis lacinia aenean sit amet', 38.48, 55);
go
insert into OrderItem (OrderId, ItemId, Quantity, ItemPrice, TotalCost) values (3, 42, 1, 5, 5);
insert into OrderItem (OrderId, ItemId, Quantity, ItemPrice, TotalCost) values (2, 142, 4, 30, 120);
insert into OrderItem (OrderId, ItemId, Quantity, ItemPrice, TotalCost) values (1, 156, 3, 21, 63);
insert into OrderItem (OrderId, ItemId, Quantity, ItemPrice, TotalCost) values (1, 53, 4, 35, 140);
insert into OrderItem (OrderId, ItemId, Quantity, ItemPrice, TotalCost) values (3, 62, 3, 43, 129);


go

