
-- INSERTS FOR TESTING CLIENT SIDE
delete from OrderItem where 1=1;

delete from [Order] where 1=1;
DBCC CHECKIDENT([Order], RESEED, 0);
delete from [Order] where 1=1;

delete from [Address] where 1=1;
DBCC CHECKIDENT([Address], RESEED, 0);
delete from [Address] where 1=1;

DBCC CHECKIDENT (Item, RESEED, 0);
delete from Item where 1=1;
DBCC CHECKIDENT (Item, RESEED, 0);
delete from [Permissions] where 1=1;
DBCC CHECKIDENT ([Permissions], RESEED, 0);

delete from Category where 1=1;
DBCC CHECKIDENT(Category, RESEED, 0);
delete from Category where 1=1;

delete from [User] where 1=1;
DBCC CHECKIDENT ([User], RESEED, 0);
delete from [User] where 1=1;

insert into Category ( [Name]) values ( 'Beverages');
insert into Category ( [Name]) values ( 'Bakery');
insert into Category ( [Name]) values ( 'Canned/Jarred Goods');
insert into Category ( [Name]) values ( 'Dairy');
insert into Category ( [Name]) values ( 'Dry/Baking Goods');
insert into Category ( [Name]) values ( 'Frozen Foods');
insert into Category ( [Name]) values ( 'Meat');
insert into Category ( [Name]) values ( 'Produce');
insert into Category ( [Name]) values ( 'Cleaners');
insert into Category ( [Name]) values ( 'Paper Goods');
insert into Category ( [Name]) values ( 'Personal Care');
insert into Category ( [Name]) values ( 'Other');
go 

insert into [Permissions] (PermissionName)
values ('Customer'), ('Admin');
go

insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Gus', 'Jost', 'sa@123.com', 'e5857b335afdf35ca81a110bc81f38682f8a89892cc597f5398dfef82d42b513', '332-411-2147',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Trude', 'Bes', 'tbes1@sogou.com', 'okz1XfRsv3', '815-234-2158',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Lew', 'Dedmam', 'ldedmam2@yale.edu', 'JdO5Vu4e', '286-724-9302',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Fawne', 'MacGinney', 'fmacginney3@ox.ac.uk', 'kUkvzLfV', '547-731-6904',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Benito', 'Cavan', 'bcavan4@bizjournals.com', 'DRXO5Pf', '295-277-3367',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Shepperd', 'Font', 'sfont5@state.gov', 'jJcb14FzD7M', '278-950-5474',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Garrot', 'Dumigan', 'gdumigan6@redcross.org', '1gzgAxbM8Woa', '342-855-3265',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Auria', 'Hogbourne', 'ahogbourne7@sitemeter.com', '0kxpjx04Chxv', '858-276-4006',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Shandee', 'McQuillen', 'smcquillen8@scientificamerican.com', 'svED2o3ujNUr', '459-863-0224',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Enid', 'Caisley', 'ecaisley9@engadget.com', 'tEmR3Do2j', '302-808-2509',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Rodina', 'Ivery', 'riverya@bing.com', 'lJ2ITaB75IU', '300-475-8336',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Gloriane', 'Fetters', 'gfettersb@marketwatch.com', 's1OTmegL', '208-807-7087',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Gloriana', 'Nowakowska', 'gnowakowskac@acquirethisname.com', 'rIr474X', '211-450-5946',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Ari', 'Vawton', 'avawtond@ted.com', 'siUFdNoGzo', '997-861-0986',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Katerine', 'Baitson', 'kbaitsone@ftc.gov', 'ooSucRSjIj6', '292-228-2748',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Brandice', 'Espinosa', 'bespinosaf@usda.gov', '72o3ou', '451-254-2350',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Rebbecca', 'Gives', 'rgivesg@themeforest.net', 'jTerUEkK', '813-503-3034',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Shurlock', 'Hame', 'shameh@princeton.edu', 'tkvAujjV', '841-933-0454',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Jeth', 'Nutbeem', 'jnutbeemi@jigsy.com', 'FSDd5RM83SdY', '268-312-1218',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Rozamond', 'Canada', 'rcanadaj@macromedia.com', '6u3gmH1gO', '167-934-6702',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Bertram', 'Slamaker', 'bslamakerk@etsy.com', 'S8R6F2x', '132-456-3145',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Cesar', 'Haycroft', 'chaycroftl@blinklist.com', '3Pkqn23z8r', '788-945-7628',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Muffin', 'Starbuck', 'mstarbuckm@163.com', 'Mgi4gvx', '831-404-4955',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Tara', 'Egginson', 'tegginsonn@macromedia.com', 'h7SctcXi', '962-408-6748',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Brett', 'Giovanazzi', 'bgiovanazzio@forbes.com', 'gVjDpdi8NswH', '794-593-4275',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Gusty', 'Goldfinch', 'ggoldfinchp@flickr.com', 'eGbFQ7rw2', '647-954-3973',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Mario', 'Timbridge', 'mtimbridgeq@oracle.com', 'iC4OgnD4O', '619-633-5692',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Leupold', 'Cawthra', 'lcawthrar@weather.com', 'RNGr763g6F7M', '997-876-4161',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Grazia', 'Duffy', 'gduffys@wufoo.com', 'C8Tt7ijh5um', '515-376-3823',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Maia', 'Waterstone', 'mwaterstonet@so-net.ne.jp', '3cAJy2kvpnzW', '918-873-9733',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Catharina', 'MacFadzan', 'cmacfadzanu@1und1.de', 'jEwQDk', '182-432-7094',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Salvador', 'Blumire', 'sblumirev@pen.io', 'hNi5ONXwcj', '230-174-3231',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Hermina', 'Windrus', 'hwindrusw@webeden.co.uk', 'QNzYoD', '709-192-1811',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Francesco', 'Wheldon', 'fwheldonx@icq.com', 'te5w7v', '893-413-3020',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Josie', 'Ethridge', 'jethridgey@photobucket.com', 'LlvdOiZf', '250-591-5214',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Leopold', 'Mavin', 'lmavinz@hp.com', 'zmTlQmzuG', '972-820-6018',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Francisca', 'Garnsey', 'fgarnsey10@ycombinator.com', 'wLwlgn', '192-335-4457',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Cate', 'Enrico', 'cenrico11@blog.com', 'yx6qjYglN', '157-792-0369',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Filbert', 'Woolfenden', 'fwoolfenden12@uiuc.edu', 'wtvKRFUcZ', '298-187-1961',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Shanta', 'Craddock', 'scraddock13@1688.com', '7AiyycQZ', '407-948-0327',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Dianemarie', 'Steels', 'dsteels14@themeforest.net', 'i7SFH8q8fc', '776-227-1015',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Libbie', 'Bielfeldt', 'lbielfeldt15@nhs.uk', '19lJljSzqs4', '155-759-1883',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Adan', 'Murtimer', 'amurtimer16@msn.com', 'suFPhrs3a1wT', '566-377-9270',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Casey', 'Garret', 'cgarret17@bloglovin.com', 'GN3JZH', '410-404-7650',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Harbert', 'Dacke', 'hdacke18@cam.ac.uk', 'qWLftwCSeaqs', '132-824-6613',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Billie', 'Kennham', 'bkennham19@mit.edu', 'G1JF7746FvHs', '411-994-7592',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Cordy', 'Toynbee', 'ctoynbee1a@ft.com', 'bIhTLHF5VaU', '462-945-2108',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Peggy', 'Goddman', 'pgoddman1b@cam.ac.uk', 'bP0teaGAbiV', '768-985-1768',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Faun', 'Peery', 'fpeery1c@youtube.com', 'ZIAqtq', '269-742-1847',2);
insert into [User] ( FirstName, LastName, Email, [Password], Phone,PermissionId) values ( 'Steffen', 'Yezafovich', 'syezafovich1d@youku.com', 'EX9KfAZCiv2', '506-202-7256',2);
go

set IDENTITY_INSERT [Address] on;
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (1, 1, '448 Sloan Circle', 'Minneapolis', 'MN', 55102, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (2, 2, '747 Vermont Point', 'Minneapolis', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (3, 3, '9 Vernon Park', 'St. Paul', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (4, 4, '4557 Karstens Park', 'St. Paul', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (5, 5, '3 Washington Place', 'Minneapolis', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (6, 6, '75428 Del Mar Crossing', 'Minneapolis', 'MN', 55408, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (7, 7, '6634 Center Hill', 'Minneapolis', 'MN', 55101, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (8, 8, '233 Shoshone Road', 'Minneapolis', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (9, 9, '61659 Algoma Lane', 'St. Paul', 'MN', 55101, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (10, 10, '74514 Anhalt Pass', 'St. Paul', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (11, 11, '5293 Claremont Court', 'Minneapolis', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (12, 12, '9162 Duke Way', 'Minneapolis', 'MN', 55102, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (13, 13, '51925 Elgar Terrace', 'Minneapolis', 'MN', 55408, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (14, 14, '021 Jenna Point', 'Minneapolis', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (15, 15, '79034 Village Green Court', 'Minneapolis', 'MN', 55104, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (16, 16, '40 Colorado Way', 'Minneapolis', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (17, 17, '43 Barby Junction', 'St. Paul', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (18, 18, '2795 Fuller Way', 'St. Paul', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (19, 19, '5059 Debra Plaza', 'St. Paul', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (20, 20, '2468 Bunting Hill', 'Minneapolis', 'MN', 55408, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (21, 21, '9967 Cardinal Pass', 'Minneapolis', 'MN', 55408, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (22, 22, '8462 Thierer Center', 'St. Paul', 'MN', 55102, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (23, 23, '84 Basil Avenue', 'Minneapolis', 'MN', 55104, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (24, 24, '3 Sycamore Circle', 'St. Paul', 'MN', 55103, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (25, 25, '3 Autumn Leaf Hill', 'St. Paul', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (26, 26, '5 Forest Run Court', 'Minneapolis', 'MN', 55102, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (27, 27, '2835 Lakewood Junction', 'St. Paul', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (28, 28, '80 Summit Circle', 'St. Paul', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (29, 29, '4 Ronald Regan Avenue', 'Minneapolis', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (30, 30, '0 Golden Leaf Lane', 'St. Paul', 'MN', 55104, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (31, 31, '62762 Summerview Junction', 'St. Paul', 'MN', 55104, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (32, 32, '3 Erie Point', 'Minneapolis', 'MN', 55102, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (33, 33, '733 Reinke Trail', 'Minneapolis', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (34, 34, '56467 Melvin Place', 'Minneapolis', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (35, 35, '8387 Northwestern Hill', 'St. Paul', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (36, 36, '2162 Truax Circle', 'St. Paul', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (37, 37, '00 Sheridan Point', 'St. Paul', 'MN', 55408, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (38, 38, '6025 Nelson Park', 'St. Paul', 'MN', 55104, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (39, 39, '64 Kenwood Pass', 'Minneapolis', 'MN', 55102, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (40, 40, '77 Hauk Road', 'Minneapolis', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (41, 41, '44928 Thackeray Parkway', 'Minneapolis', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (42, 42, '9 Buhler Park', 'Minneapolis', 'MN', 55408, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (43, 43, '71 Muir Terrace', 'St. Paul', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (44, 44, '4 Division Court', 'Minneapolis', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (45, 45, '7 Summit Circle', 'St. Paul', 'MN', 55103, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (46, 46, '62 Moland Park', 'St. Paul', 'MN', 55401, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (47, 47, '6 Birchwood Plaza', 'St. Paul', 'MN', 55406, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (48, 48, '8 Darwin Point', 'Minneapolis', 'MN', 55104, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (49, 49, '6 Division Avenue', 'Minneapolis', 'MN', 55404, 'US');
insert into [Address] (AddressId, UserId, Street, City, [State], PostalCode, CountryCode) values (50, 50, '115 Merry Terrace', 'St. Paul', 'MN', 55404, 'US');
set IDENTITY_INSERT [Address] off;
go

insert into [Order] (UserId, TotalCost, DateCreated) values (1, 10, '3/8/2022');
insert into [Order] (UserId, TotalCost, DateCreated) values (2, 92, '3/11/2022');
insert into [Order] (UserId, TotalCost, DateCreated) values (3, 68, '9/19/2021');
go

insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Beef Rib Eye', 'nunc donec', 51.34, 66);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Wine', 'et eros vestibulum ac', 31.79, 7);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Choclate Cake', 'nam congue', 96.42, 49);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Lettuce', 'libero non mattis pulvinar nulla', 19.88, 52);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Eggplant', 'volutpat', 77.61, 24);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Olive Oil', 'ut nunc vestibulum', 20.02, 54);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'American Cheese', 'massa quis augue luctus tincidunt', 13.75, 72);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Cod Fillet', 'nullam sit amet', 74.84, 98);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Carbonated Water - Blackberry', 'ac tellus semper', 90.42, 32);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Canada Dry', 'nec sem duis aliquam', 2.28, 94);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Flour', 'libero quis orci nullam molestie', 97.12, 34);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Coconut Flakes', 'at', 91.86, 1);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Broom', 'eget elit sodales scelerisque', 97.75, 27);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Corona', 'magna vestibulum', 52.42, 2);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Juice - Orange, Concentrate', 'ultrices enim lorem ipsum dolor', 48.41, 56);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Pork Sausage', 'etiam pretium iaculis justo', 80.93, 25);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Ground Cumin', 'mattis odio donec', 21.66, 40);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Almond', 'eu mi nulla', 10.77, 59);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Apple Juice, 1.36l', 'ultrices', 30.43, 30);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Sour Cream', 'ultrices mattis odio donec vitae', 46.86, 27);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Cheddar Cheese, Shredded', 'rutrum', 58.88, 24);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Orange', 'egestas metus aenean fermentum', 72.55, 74);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Bread, White', 'blandit', 97.25, 22);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Potato Chips, Salt & Vinegar', 'nulla nisl nunc nisl', 16.8, 42);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Duck Breast', 'posuere cubilia', 45.73, 66);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Beans, Chinese', 'condimentum curabitur in libero', 65.16, 6);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Tomatoes', 'dolor sit amet consectetuer', 12.64, 41);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Mini Cheesecake', 'cursus urna ut', 76.77, 44);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Pam Cooking Spray', 'nulla integer pede', 26.45, 43);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Chocolate', 'nisl nunc nisl duis bibendum', 53.83, 60);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5,'Coffee, Columbian Roast', 'elementum', 51.83, 15);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Vanilla Icecream', 'donec pharetra', 33.23, 66);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'French Bread', 'nisl', 90.67, 73);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Cherries, Canned', 'vulputate ut ultrices vel augue', 15.25, 16);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Black Pepper', 'elit sodales scelerisque', 66.88, 12);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Beef Tenderloin', 'sit amet eros', 92.25, 8);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Beef Top Butt', 'praesent lectus', 3.07, 54);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Bacardi Mojito', 'hac', 20.36, 62);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Pepper - Scotch Bonnet', 'nulla ac enim in tempor', 88.03, 44);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Campbells Chicken Noodle', 'nunc purus phasellus in', 33.51, 99);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Chow Mein', 'dolor morbi', 74.64, 31);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Banana', 'lacus morbi', 47.37, 97);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Apples', 'ultrices erat tortor sollicitudin', 2.96, 17);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Pecan Pie', 'in', 94.48, 95);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Tuna - Canned, Flaked, Light', 'faucibus orci luctus', 65.86, 4);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Cookie Double Choco', 'integer aliquet massa id lobortis', 93.29, 94);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (2, 'Assorted Desserts', 'augue quam sollicitudin', 15.94, 32);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Yellow Onion', 'erat', 38.66, 13);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Sugar - Brown, Individual', 'dui vel nisl duis', 38.86, 6);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Vanilla Yogurt', 'nulla elit ac', 4.67, 79);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Ultra', 'sapien', 98.19, 45);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Kellogs Cereal', 'id nisl venenatis lacinia', 96.78, 71);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Lima Beans, Canned', 'lacinia aenean sit amet justo', 4.21, 57);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Tomatoes', 'velit donec diam neque vestibulum', 41.33, 83);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Blueberry Muffin Mix', 'quisque', 89.69, 52);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Flushable Wipes', 'in tempor', 86.81, 12);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Bleach', 'vivamus vel nulla eget', 81.82, 2);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Dog Food', 'curae mauris', 6.71, 71);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Brandy', 'in', 84.63, 6);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Chantrelle Mushrroms, Fresh', 'nam congue risus', 31.21, 92);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Windex', 'integer', 2.86, 53);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Cup - Paper 10oz 92959', 'cras non', 76.43, 16);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Gatorade, Cool Blue Raspberry', 'neque duis bibendum morbi', 67.12, 35);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Dove Body Wash', 'sollicitudin mi sit amet lobortis', 86.3, 77);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Hand Soap', 'tincidunt', 55.4, 34);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Dawn Dish Soap', 'ligula sit amet eleifend pede', 75.89, 31);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Cabbage, Green', 'luctus', 30.85, 26);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Onion Powder', 'ultrices posuere cubilia', 22.59, 77);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Onion, Red', 'leo', 88.14, 39);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (4, 'Cottage Cheese - Brie Roitelet', 'sapien', 20.5, 36);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Nothern Beans, Canned', 'morbi', 28.0, 48);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Campbells Beef With Veg', 'est', 44.3, 52);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Paprika', 'sit amet', 65.13, 79);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Coffee, Decaf Colombian', 'sit amet justo morbi', 44.62, 86);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (8, 'Lettuce, Iceberg', 'lorem', 53.74, 56);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Sprite, Diet', 'suscipit ligula in', 27.48, 51);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Sprite,', 'suscipit ligula in', 27.48, 51);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Beef Ground Medium', 'ut volutpat sapien', 78.73, 2);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Halibut - Steaks', 'vitae nisi', 57.14, 53);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Beef Inside Round', 'nibh in lectus pellentesque at', 40.23, 93);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Cake Sheet Combo Party Pack', 'sed lacus', 6.3, 92);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (11, 'Makeup Remover', 'ligula', 23.25, 66);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (1, 'Mango Juice', 'at nibh in hac', 62.18, 9);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (7, 'Lettuce - Radicchio', 'euismod scelerisque quam turpis adipiscing', 74.29, 46);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Basil Pesto Sauce', 'id sapien in sapien', 51.22, 86);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Toilet Paper', 'erat', 57.15, 24);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Paper Plates', 'eget orci', 69.91, 63);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (5, 'Penne Pasta', 'at nibh in hac habitasse', 35.58, 30);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Cheese Curdes', 'volutpat in congue etiam justo', 92.08, 95);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Mango, Frozen', 'odio', 93.38, 82);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Fish Sticks', 'lorem', 11.93, 85);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Strawberries, Frozen', 'consectetuer adipiscing elit proin interdum', 42.57, 41);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Campbells Tomato Soup', 'venenatis lacinia aenean sit amet', 38.48, 55);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (9, 'Lysol Spray', 'at nibh in hac habitasse', 35.58, 30);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (10, 'Napkins', 'volutpat in congue etiam justo', 92.08, 95);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Raspberries, Frozen', 'odio', 93.38, 82);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (12, 'Cat Food', 'lorem', 11.93, 85);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (6, 'Blueberries, Frozen', 'consectetuer adipiscing elit proin interdum', 42.57, 41);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Baked Beans', 'venenatis lacinia aenean sit amet', 38.48, 55);
insert into Item (CategoryId, [Name], [Description], Price, Inventory) values (3, 'Campbells Potato Soup', 'venenatis lacinia aenean sit amet', 38.48, 55);
go

insert into OrderItem (OrderId, ItemId, Quantity, ItemPrice, TotalCost) values (3, 42, 1, 5, 5);
insert into OrderItem (OrderId, ItemId, Quantity, ItemPrice, TotalCost) values (2, 100, 4, 30, 120);
insert into OrderItem (OrderId, ItemId, Quantity, ItemPrice, TotalCost) values (1, 94, 3, 21, 63);
insert into OrderItem (OrderId, ItemId, Quantity, ItemPrice, TotalCost) values (1, 53, 4, 35, 140);
insert into OrderItem (OrderId, ItemId, Quantity, ItemPrice, TotalCost) values (3, 62, 3, 43, 129);

go